# This is a basic workflow to help you get started with Actions

name: Homebrew test

on:
  workflow_dispatch:
  

jobs:
  homebrew:
    runs-on: macos-latest

    steps:
      - name: Setup homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Update homebrew
        run: |
          brew update
          brew update
          brew doctor
          
      - name: Create formula
        run: |
          brew create --set-name dbt-redshift-1.5.1 https://github.com/dbt-labs/dbt-redshift/releases/download/v1.5.1/dbt-redshift-1.5.1.tar.gz
          
      - name: Add resources
        run: |
          brew update-python-resources /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dbt-redshift-1.5.1.rb --package-name dbt-redshift-1.5.1
