# This is a basic workflow to help you get started with Actions

name: Homebrew install testing

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  homebrew:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        adapter: ['dbt-postgres', 'dbt-redshift', 'dbt-snowflake', 'dbt-bigquery']

    steps:
      - name: Brew install ${{ matrix.adapter }}
        run: |
          brew update
          brew install git
          brew tap dbt-labs/dbt
          brew install ${{ matrix.adapter }}
