# This is a basic workflow to help you get started with Actions

name: Homebrew test

on:
  workflow_dispatch:
  

jobs:
  homebrew:
    runs-on: macos-latest

    steps:
      - name: Setup homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Update homebrew
        run: |
          brew update
          brew update
          brew cleanup
          brew doctor
           
      - name: Add resources
        run: |
          cd
          ls
          brew update-python-resources dbt-redshift-1.5.1.rb --package-name dbt-redshift-1.5.1
