# **what?**
# Mirrors issues into Jira. Includes the information: title
# description, GitHub Issue ID and URL

# **why?**
# Jira is our tool for tracking and we need to see these issues in there

# **when?**
# On issue creation or when an issue is labeled `Jira`

name: Jira Issue Creation

on:
  issues:
    types: [labeled, unlabeled]
    
permissions:
  issues: write

jobs:
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.generate-matrix.outputs.services }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          SERVICES='${{ toJSON(github.event.issue.labels.*.name) }}'
          echo ::set-output name=services::${SERVICES}
  # ------------------------
  my_echo:
    runs-on: ubuntu-latest
    needs:
      - say_hello
    steps:
      - name: Echo previous outputs
        run: echo '${{ { "labels": toJSON(needs.say_hello.outputs) , "customfield_10045": "github.event.issue.html_url", "customfield_10046": github.event.issue.number } }}'
