# **what?**
# Mirrors issues into Jira. Includes the information: title
# description, GitHub Issue ID and URL

# **why?**
# Jira is our tool for tracking and we need to see these issues in there

# **when?**
# On issue creation or when an issue is labeled `Jira`

name: Jira Issue Creation

on:
  issues:
    types: [labeled, unlabeled]
    
permissions:
  issues: write

jobs:
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.generate-matrix.outputs.services }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          SERVICES='${{ toJSON(github.event.issue.labels.*.name) }}'
          echo ::set-output name=services::${SERVICES}
  # ------------------------
  my_echo:
    runs-on: ubuntu-latest
    needs:
      - say_hello
    steps:
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.say_hello.outputs) }}"
  my_matrix:
    runs-on: ubuntu-latest
    needs:
      - my_echo
      - say_hello
    strategy:
      matrix:
        service: ${{ fromJSON(needs.say_hello.outputs.services) }}
    steps:
      - name: Matrix => (${{ matrix.service }} ${{ matrix.version}})
        run: |
          echo ${{ matrix.service }}
    
      - name: Script
        run: |
          echo "${{ github.event.issue.assignee.login }}"
          labels="${{ github.event.issue.labels.*.name }}"
          labels+="redshift"
          echo "$labels"

    
