# **what?**
# Mirrors issues into Jira. Includes the information: title
# description, GitHub Issue ID and URL

# **why?**
# Jira is our tool for tracking and we need to see these issues in there

# **when?**
# On issue creation or when an issue is labeled `Jira`

name: Jira Issue Creation

on:
  issues:
    types: [labeled, unlabeled]
    
permissions:
  issues: write

jobs:
  find-labels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.generate-labels.outputs.labels }}
    steps:
      - name: Generate Labels
        id: generate-labels
        run: |
          LABELS='${{ toJSON(github.event.issue.labels.*.name) }}'
          echo ::set-output name=services::${LABELS}
          
  add-labels:
    runs-on: ubuntu-latest
    needs:
      - find-labels
    strategy:
      matrix:
        label: ${{ fromJSON(needs.find-labels.outputs.labels) }}
    steps: 
       - name: Make comment on Jira issue
         run: echo ${{ matrix.label }}
