# **what?**
# Mirrors issues into Jira. Includes the information: title
# description, GitHub Issue ID and URL

# **why?**
# Jira is our tool for tracking and we need to see these issues in there

# **when?**
# On issue creation or when an issue is labeled `Jira`

name: Jira Issue Creation

on:
  issues:
    types: [labeled, unlabeled]
    
permissions:
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'labeled' && github.event.label.name != 'jira')
    steps: 
    - name: Script
      run: |
        echo ${{ github.event.issue.labels.name }}
    
