# **what?**
# Mirrors issues into Jira. Includes the information: title
# description, GitHub Issue ID and URL

# **why?**
# Jira is our tool for tracking and we need to see these issues in there

# **when?**
# On issue creation or when an issue is labeled `Jira`

name: Jira Label Mirroring

on:
  issues:
    types: [labeled, unlabeled]
    
permissions:
  issues: read

jobs:
  add-label:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'labeled' && startsWith(github.event.issue.title, '[CT-'))
    steps:
      - name: Extract issue from title
        id: extract
        env:
          TITLE: "${{ github.event.issue.title }}"
        run: |
          jira=$(echo -n $TITLE | awk '{print $1}' | awk -F'[][]' '{print $2}')
          echo ::set-output name=jira::$jira
          
      - name: Setup Jira
        uses: atlassian/gajira-cli@v2.0.2

      - name: Add label
        run: jira labels add ${{ needs.create-issue.outputs.issueId }} ${{ steps.extract.outputs.jira }}

  remove-label:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'unlabeled' && startsWith(github.event.issue.title, '[CT-'))
    steps:
      - name: Extract issue from title
        id: extract
        env:
          TITLE: "${{ github.event.issue.title }}"
        run: |
          jira=$(echo -n $TITLE | awk '{print $1}' | awk -F'[][]' '{print $2}')
          echo ::set-output name=jira::$jira
          
      - name: Setup Jira
        uses: atlassian/gajira-cli@v2.0.2

      - name: Remove label
        run: jira labels remove ${{ needs.create-issue.outputs.issueId }} ${{ steps.extract.outputs.jira }}
