name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: 'leahwicz/testRepo'
        token: ${{ secrets.PAT_TOKEN }}
        event-type: 'scheduled-release-branch'
    - uses: actions/github-script@v6
      id: api-call
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          try {
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'leahwicz',
              repo: 'testRepo',
              workflow_id: 'main.yml',
              ref: 'testBranch'
            })
            console.log(result);
          } catch(error) {
            console.error(error);
            core.setFailed(error);
          }
    - name: Print
      run: |
        echo "${{steps.api-call.outputs.result}}"
