name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch: [master, testBranch]
    steps:
    
    - name: Call CI workflow for ${{ matrix.branch }} branch
      id: trigger-step
      uses: aurelien-baudet/workflow-dispatch@v2.1.1
      with:
        workflow: main.yml
        ref: ${{ matrix.branch }}
        token: ${{ secrets.PAT_TOKEN }}
      
    - name: Another step that can handle the result
      if: always()
      run: |
        echo "Another Workflow conclusion: ${{ steps.trigger-step.outputs.workflow-conclusion }}"
      
    - name: Another step that can handle the result
      if: ${{ always() && !contains(steps.trigger-step.outputs.workflow-conclusion,'success') }}
      run: |
        echo "Another Workflow conclusion: ${{ steps.trigger-step.outputs.workflow-conclusion }}"
