name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: api-call
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          return await github.rest.actions.createWorkflowDispatch({
            owner: 'leahwicz',
            repo: 'testRepo',
            workflow_id: 'main.yml',
            ref: 'testBranch'
          })
        result-encoding: string
    - name: Print
      run: |
        echo "${{steps.api-call.outputs.result}}"
