# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - name: Testing mirror action
      uses: leahwicz/mirror-devops-workitems-action@master
      with:
        area-path: ActionsTest\TestPath\TestPath2
        repo-token: "${{ secrets.GH_TOKEN }}"
        ado-token: "${{ secrets.ADO_SECRET }}"
        org-name: leantk
        label-filter: "Area: ABTT"
        labels-for-issues: "P1,Area: ABTT"
        issue-prefix: "[DTS"
        work-item-status: Active 
