name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, testBranch]
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: 'leahwicz/testRepo'
        token: ${{ secrets.PAT_TOKEN }}
        event-type: 'scheduled-release-branch'
        client-payload: '{"ref": "${{branch}}"}'
