# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - name: Testing mirror action
      uses: leahwicz/mirror-devops-workitems-action@master
      with:
        area-path: /DevOps/Pipelines/Integrations
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        ado-token: "${{ secrets.ADO_TOKEN }}"
        org-name: leantk
        label-filter: "Area: ABTT"
        labels-for-issues: "Area: ABTT, P1"
        work-item-type: bug
        issue-prefix: "[DTS"
